[project]
name = "renovate-scientific-python-spec-0-test"
version = "0.1.0"
description = "Test project for renovate-scientific-python-spec-0"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = ["numpy>=1.25.0"]
